In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

In [2]:
from src.config import CREDIT_RISK_DATASET
from src.preprocessing import *

In [3]:
from pathlib import Path
print(Path.cwd())

d:\Projects\Credit-Risk-Analysis-System\notebooks

In [4]:
# ============================================================================
# Project Path Setup
# ============================================================================

from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

In [5]:
from src.config import CREDIT_RISK_DATASET
from src.preprocessing import load_dataset

df = load_dataset(CREDIT_RISK_DATASET)

df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [6]:
rows, columns = get_dataset_shape(df)

print(f"Rows    : {rows}")
print(f"Columns : {columns}")

Rows    : 32581
Columns : 12

In [7]:
head, tail = display_sample_records(df)

display(head)
display(tail)

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
32576,57,53000,MORTGAGE,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30
32577,54,120000,MORTGAGE,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19
32578,65,76000,RENT,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28
32579,56,150000,MORTGAGE,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26
32580,66,42000,RENT,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30

In [8]:
column_information = get_column_information(df)

display(column_information)

,Column,Data Type,Non-Null Count,Missing Values,Unique Values
0,person_age,int64,32581,0,58
1,person_income,int64,32581,0,4295
2,person_home_ownership,str,32581,0,4
3,person_emp_length,float64,31686,895,36
4,loan_intent,str,32581,0,6
5,loan_grade,str,32581,0,7
6,loan_amnt,int64,32581,0,753
7,loan_int_rate,float64,29465,3116,348
8,loan_status,int64,32581,0,2
9,loan_percent_income,float64,32581,0,77
10,cb_person_default_on_file,str,32581,0,2
11,cb_person_cred_hist_length,int64,32581,0,29

In [9]:
missing_values = check_missing_values(df)

display(missing_values)

                   Missing Values  Missing Percentage
loan_int_rate                3116                9.56
person_emp_length             895                2.75

In [10]:
duplicate_records = check_duplicate_records(df)

print(f"Duplicate Records : {duplicate_records}")

Duplicate Records : 165

In [11]:
memory_usage = get_memory_usage(df)

print(f"Memory Usage : {memory_usage:.2f} MB")

Memory Usage : 8.63 MB

In [12]:
dataset_summary = generate_dataset_summary(df)

dataset_summary

{'Rows': 32581,
 'Columns': 12,
 'Numerical Columns': 8,
 'Categorical Columns': 4,
 'Duplicate Rows': 165,
 'Memory Usage (MB)': 8.63}

In [13]:
numerical_summary = get_numerical_summary(df)

display(numerical_summary)

,count,mean,std,min,25%,50%,75%,max
person_age,32581.0,27.734600,6.348078,20.00,23.00,26.00,30.00,144.00
person_income,32581.0,66074.848470,61983.119168,4000.00,38500.00,55000.00,79200.00,6000000.00
person_emp_length,31686.0,4.789686,4.142630,0.00,2.00,4.00,7.00,123.00
loan_amnt,32581.0,9589.371106,6322.086646,500.00,5000.00,8000.00,12200.00,35000.00
loan_int_rate,29465.0,11.011695,3.240459,5.42,7.90,10.99,13.47,23.22
loan_status,32581.0,0.218164,0.413006,0.00,0.00,0.00,0.00,1.00
loan_percent_income,32581.0,0.170203,0.106782,0.00,0.09,0.15,0.23,0.83
cb_person_cred_hist_length,32581.0,5.804211,4.055001,2.00,3.00,4.00,8.00,30.00

In [14]:
categorical_summary = get_categorical_summary(df)

display(categorical_summary)

                           count unique        top   freq
person_home_ownership      32581      4       RENT  16446
loan_intent                32581      6  EDUCATION   6453
loan_grade                 32581      7          A  10777
cb_person_default_on_file  32581      2          N  26836

In [15]:
duplicate_records = get_duplicate_records(df)

display(duplicate_records.head(10))

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
14,23,115000,RENT,2.0,EDUCATION,A,35000,7.90,0,0.30,N,4
238,22,183000,MORTGAGE,3.0,EDUCATION,A,1000,NaN,0,0.01,N,2
252,24,85000,RENT,5.0,MEDICAL,B,25000,10.62,0,0.29,N,4
591,26,20000,MORTGAGE,5.0,MEDICAL,A,4800,5.99,0,0.24,N,3
740,21,21600,OWN,NaN,VENTURE,A,7125,6.99,0,0.33,N,3
817,22,22000,OWN,1.0,DEBTCONSOLIDATION,D,8500,15.05,0,0.39,N,4
920,26,50000,RENT,10.0,PERSONAL,B,18950,NaN,1,0.38,N,3
1094,22,24449,OWN,2.0,VENTURE,B,1800,11.89,0,0.07,N,4
1142,25,60000,RENT,3.0,PERSONAL,A,17000,6.91,0,0.28,N,2
1453,23,20400,RENT,2.0,MEDICAL,A,1200,7.90,0,0.06,N,2

In [16]:
validation_report = validate_dataset(df)

validation_report

{'Dataset Empty': False,
 'Contains Missing Values': True,
 'Contains Duplicates': True,
 'Total Missing Values': 4011,
 'Total Duplicate Rows': 165,
 'Validation Status': 'Passed'}

In [17]:
print("Before :", df.shape)

cleaned_df = remove_duplicate_records(df)

print("After  :", cleaned_df.shape)

Before : (32581, 12)
After  : (32416, 12)

In [18]:
check_duplicate_records(cleaned_df)

np.int64(0)

In [19]:
missing_report = analyze_missing_values(cleaned_df)

display(missing_report)

                   Missing Values  Missing Percentage Data Type
loan_int_rate                3095                9.55   float64
person_emp_length             887                2.74   float64

In [20]:
filled_df = fill_missing_values(cleaned_df)

check_missing_values(filled_df)

Empty DataFrame
Columns: [Missing Values, Missing Percentage]
Index: []

In [21]:
data_types = validate_data_types(filled_df)

display(data_types)

                                                Column Data Type
person_age                                  person_age     int64
person_income                            person_income     int64
person_home_ownership            person_home_ownership       str
person_emp_length                    person_emp_length   float64
loan_intent                                loan_intent       str
loan_grade                                  loan_grade       str
loan_amnt                                    loan_amnt     int64
loan_int_rate                            loan_int_rate   float64
loan_status                                loan_status     int64
loan_percent_income                loan_percent_income   float64
cb_person_default_on_file    cb_person_default_on_file       str
cb_person_cred_hist_length  cb_person_cred_hist_length     int64

In [22]:
from src.config import INTERIM_DATA_DIR

save_cleaned_dataset(
    filled_df,
    INTERIM_DATA_DIR / "cleaned_data.csv"
)

In [23]:
import os

os.path.exists(
    INTERIM_DATA_DIR / "cleaned_data.csv"
)

True